// Generated by TMBtools: do not edit by hand
#define TMB_LIB_INIT R_init_tsissm_TMBExports
#include <TMB.hpp>
#include "issmextra.h"
#include "distfun.h"
#include "garchfun.h"
#include "issmconstant.hpp"
#include "issmconstantlambda.hpp"
#include "issmgarch.hpp"
#include "issmgarchlambda.hpp"
#include <Eigen/Sparse>
#ifndef M_PI
#define M_PI 3.141592653589793116
#endif

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "constant") {
    return issmconstant(this);
  } else if (model == "constantlambda") {
    return issmconstantlambda(this);
  } else if (model == "garch"){
    return issmgarch(this);
  } else if (model == "garchlambda") {
    return issmgarchlambda(this);
  } else{
    Rf_error("Unknown model.");
  }
  return 0;
}
