// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// initialize_states
Eigen::MatrixXd initialize_states(const Eigen::Map<Eigen::VectorXd>& y, const Eigen::Map<Eigen::VectorXd>& good, const Eigen::Map<Eigen::VectorXi>& valid_index, const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::VectorXd>& kappa, Eigen::Map<Eigen::VectorXd> V, Eigen::Map<Eigen::VectorXd> allpars, const Eigen::Map<Eigen::VectorXi>& findex, const Eigen::Map<Eigen::VectorXi>& fpindex, const Eigen::Map<Eigen::VectorXi>& ppindex, const Eigen::Map<Eigen::VectorXi>& fshape, const Eigen::Map<Eigen::VectorXi>& modeli, const Eigen::Map<Eigen::VectorXd>& issmpars, const double lambda);
RcppExport SEXP _tsissm_initialize_states(SEXP ySEXP, SEXP goodSEXP, SEXP valid_indexSEXP, SEXP XSEXP, SEXP kappaSEXP, SEXP VSEXP, SEXP allparsSEXP, SEXP findexSEXP, SEXP fpindexSEXP, SEXP ppindexSEXP, SEXP fshapeSEXP, SEXP modeliSEXP, SEXP issmparsSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type good(goodSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type valid_index(valid_indexSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type V(VSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type allpars(allparsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type findex(findexSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type fpindex(fpindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type ppindex(ppindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type fshape(fshapeSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type modeli(modeliSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type issmpars(issmparsSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_states(y, good, valid_index, X, kappa, V, allpars, findex, fpindex, ppindex, fshape, modeli, issmpars, lambda));
    return rcpp_result_gen;
END_RCPP
}
// issfilter_constant
Rcpp::List issfilter_constant(Eigen::Map<Eigen::MatrixXd>& F0, Eigen::Map<Eigen::MatrixXd>& F1, Eigen::Map<Eigen::MatrixXd>& F2, Eigen::Map<Eigen::VectorXd>& w, Eigen::Map<Eigen::VectorXd>& g, Eigen::Map<Eigen::VectorXd>& y, Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::VectorXd>& kappa, Eigen::Map<Eigen::VectorXd>& xseed, Eigen::Map<Eigen::VectorXd>& good, Rcpp::IntegerVector& mdim, const double lambda);
RcppExport SEXP _tsissm_issfilter_constant(SEXP F0SEXP, SEXP F1SEXP, SEXP F2SEXP, SEXP wSEXP, SEXP gSEXP, SEXP ySEXP, SEXP XSEXP, SEXP kappaSEXP, SEXP xseedSEXP, SEXP goodSEXP, SEXP mdimSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F1(F1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type xseed(xseedSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type good(goodSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(issfilter_constant(F0, F1, F2, w, g, y, X, kappa, xseed, good, mdim, lambda));
    return rcpp_result_gen;
END_RCPP
}
// issfilter_dynamic
Rcpp::List issfilter_dynamic(Eigen::Map<Eigen::MatrixXd>& F0, Eigen::Map<Eigen::MatrixXd>& F1, Eigen::Map<Eigen::MatrixXd>& F2, Eigen::Map<Eigen::VectorXd>& w, Eigen::Map<Eigen::VectorXd>& g, Eigen::Map<Eigen::VectorXd>& y, Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::VectorXd>& kappa, Eigen::Map<Eigen::VectorXd>& xseed, Eigen::Map<Eigen::VectorXd>& good, Eigen::Map<Eigen::VectorXd>& eta, Eigen::Map<Eigen::VectorXd>& delta, Rcpp::IntegerVector& mdim, Eigen::Map<Eigen::VectorXi>& vmodel, Eigen::Map<Eigen::VectorXd>& initial_arch, Eigen::Map<Eigen::VectorXd>& initial_variance, const double omega, const double lambda);
RcppExport SEXP _tsissm_issfilter_dynamic(SEXP F0SEXP, SEXP F1SEXP, SEXP F2SEXP, SEXP wSEXP, SEXP gSEXP, SEXP ySEXP, SEXP XSEXP, SEXP kappaSEXP, SEXP xseedSEXP, SEXP goodSEXP, SEXP etaSEXP, SEXP deltaSEXP, SEXP mdimSEXP, SEXP vmodelSEXP, SEXP initial_archSEXP, SEXP initial_varianceSEXP, SEXP omegaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F1(F1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type xseed(xseedSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type good(goodSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi>& >::type vmodel(vmodelSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type initial_arch(initial_archSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type initial_variance(initial_varianceSEXP);
    Rcpp::traits::input_parameter< const double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(issfilter_dynamic(F0, F1, F2, w, g, y, X, kappa, xseed, good, eta, delta, mdim, vmodel, initial_arch, initial_variance, omega, lambda));
    return rcpp_result_gen;
END_RCPP
}
// isspredict_constant
Rcpp::List isspredict_constant(Eigen::Map<Eigen::MatrixXd>& F0, Eigen::Map<Eigen::MatrixXd>& F1, Eigen::Map<Eigen::MatrixXd>& F2, Eigen::Map<Eigen::VectorXd>& w, Eigen::Map<Eigen::VectorXd>& g, Eigen::Map<Eigen::MatrixXd>& E, Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::VectorXd>& kappa, Eigen::Map<Eigen::VectorXd>& xseed, Rcpp::IntegerVector& mdim);
RcppExport SEXP _tsissm_isspredict_constant(SEXP F0SEXP, SEXP F1SEXP, SEXP F2SEXP, SEXP wSEXP, SEXP gSEXP, SEXP ESEXP, SEXP XSEXP, SEXP kappaSEXP, SEXP xseedSEXP, SEXP mdimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F1(F1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type xseed(xseedSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type mdim(mdimSEXP);
    rcpp_result_gen = Rcpp::wrap(isspredict_constant(F0, F1, F2, w, g, E, X, kappa, xseed, mdim));
    return rcpp_result_gen;
END_RCPP
}
// isspredict_dynamic
Rcpp::List isspredict_dynamic(Eigen::Map<Eigen::MatrixXd>& F0, Eigen::Map<Eigen::MatrixXd>& F1, Eigen::Map<Eigen::MatrixXd>& F2, Eigen::Map<Eigen::VectorXd>& w, Eigen::Map<Eigen::VectorXd>& g, Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::VectorXd>& kappa, Eigen::Map<Eigen::VectorXd>& xseed, Eigen::Map<Eigen::VectorXd>& e, Eigen::Map<Eigen::MatrixXd>& Z, Eigen::Map<Eigen::VectorXd>& init_arch, Eigen::Map<Eigen::VectorXd>& init_garch, Eigen::Map<Eigen::VectorXd>& alpha, Eigen::Map<Eigen::VectorXd>& beta, const double variance_intercept, Eigen::Map<Eigen::VectorXi>& order, Rcpp::IntegerVector& mdim);
RcppExport SEXP _tsissm_isspredict_dynamic(SEXP F0SEXP, SEXP F1SEXP, SEXP F2SEXP, SEXP wSEXP, SEXP gSEXP, SEXP XSEXP, SEXP kappaSEXP, SEXP xseedSEXP, SEXP eSEXP, SEXP ZSEXP, SEXP init_archSEXP, SEXP init_garchSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP variance_interceptSEXP, SEXP orderSEXP, SEXP mdimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F1(F1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type xseed(xseedSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type e(eSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type init_arch(init_archSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type init_garch(init_garchSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type variance_intercept(variance_interceptSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi>& >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type mdim(mdimSEXP);
    rcpp_result_gen = Rcpp::wrap(isspredict_dynamic(F0, F1, F2, w, g, X, kappa, xseed, e, Z, init_arch, init_garch, alpha, beta, variance_intercept, order, mdim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsissm_initialize_states", (DL_FUNC) &_tsissm_initialize_states, 14},
    {"_tsissm_issfilter_constant", (DL_FUNC) &_tsissm_issfilter_constant, 12},
    {"_tsissm_issfilter_dynamic", (DL_FUNC) &_tsissm_issfilter_dynamic, 18},
    {"_tsissm_isspredict_constant", (DL_FUNC) &_tsissm_isspredict_constant, 10},
    {"_tsissm_isspredict_dynamic", (DL_FUNC) &_tsissm_isspredict_dynamic, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsissm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
