# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

issestimation <- function(f0_, f1_, f2_, w_, g_, y_, mdim, lambda_, xreg_, kappa_) {
    .Call(`_tsissm_issestimation`, f0_, f1_, f2_, w_, g_, y_, mdim, lambda_, xreg_, kappa_)
}

issfilter <- function(f0_, f1_, f2_, w_, g_, y_, mdim, lambda_, xreg_, kappa_, xseed_) {
    .Call(`_tsissm_issfilter`, f0_, f1_, f2_, w_, g_, y_, mdim, lambda_, xreg_, kappa_, xseed_)
}

isspredict <- function(f0_, f1_, f2_, w_, g_, error_, mdim, xreg_, kappa_, xseed_) {
    .Call(`_tsissm_isspredict`, f0_, f1_, f2_, w_, g_, error_, mdim, xreg_, kappa_, xseed_)
}

