# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.initialize_states <- function(y, good, valid_index, X, kappa, V, allpars, findex, fpindex, ppindex, fshape, modeli, issmpars, lambda) {
    .Call(`_tsissm_initialize_states`, y, good, valid_index, X, kappa, V, allpars, findex, fpindex, ppindex, fshape, modeli, issmpars, lambda)
}

.issfilter_constant <- function(F0, F1, F2, w, g, y, X, kappa, xseed, good, mdim, lambda) {
    .Call(`_tsissm_issfilter_constant`, F0, F1, F2, w, g, y, X, kappa, xseed, good, mdim, lambda)
}

.issfilter_dynamic <- function(F0, F1, F2, w, g, y, X, kappa, xseed, good, eta, delta, mdim, vmodel, initial_arch, initial_variance, omega, lambda) {
    .Call(`_tsissm_issfilter_dynamic`, F0, F1, F2, w, g, y, X, kappa, xseed, good, eta, delta, mdim, vmodel, initial_arch, initial_variance, omega, lambda)
}

.isspredict_constant <- function(F0, F1, F2, w, g, E, X, kappa, xseed, mdim) {
    .Call(`_tsissm_isspredict_constant`, F0, F1, F2, w, g, E, X, kappa, xseed, mdim)
}

.isspredict_dynamic <- function(F0, F1, F2, w, g, X, kappa, xseed, e, Z, init_arch, init_garch, alpha, beta, variance_intercept, order, mdim) {
    .Call(`_tsissm_isspredict_dynamic`, F0, F1, F2, w, g, X, kappa, xseed, e, Z, init_arch, init_garch, alpha, beta, variance_intercept, order, mdim)
}

